# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: '1MTEserver2019'

steps:
- script: Xmti.Client.exe partialRestore -l -i d:test.txt --som 00:00:02;00 --eom 00:00:20;03 -o d:\Media1\MTE_2.5.5.1\name'
  displayName: 'Run a one-line script'
  workingDirectory: c:\build_agents\test_1\xmti\

